# Generated by Django 5.2 on 2026-01-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ansi', models.CharField(blank=True, max_length=255, null=True)),
                ('name_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name_ansi', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name_uni', models.CharField(blank=True, max_length=100, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uni', models.CharField(max_length=50)),
                ('full_name_ansi', models.CharField(max_length=50)),
                ('full_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, choices=[('assistant_registrar', 'Assistant Registrar'), ('section_officer', 'Section Officer'), ('computer_oparator', 'Computer Oparator'), ('office_assistant', 'Office Assistant')], max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('office_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['joining_date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uni', models.CharField(max_length=50)),
                ('full_name_ansi', models.CharField(max_length=50)),
                ('full_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('office_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['joining_date'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, unique=True)),
                ('name_ansi', models.CharField(max_length=255, unique=True)),
                ('name_uni', models.CharField(max_length=255, unique=True)),
                ('short_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name_ansi', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name_uni', models.CharField(blank=True, max_length=100, null=True)),
                ('location_en', models.CharField(blank=True, max_length=255, null=True)),
                ('location_ansi', models.CharField(blank=True, max_length=255, null=True)),
                ('location_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='ExternalTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uni', models.CharField(max_length=50)),
                ('full_name_ansi', models.CharField(max_length=50)),
                ('full_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.department')),
            ],
            options={
                'verbose_name': 'External Teacher',
                'verbose_name_plural': 'External Teachers',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='teachers.university'),
        ),
    ]
