# Generated by Django 5.2.4 on 2026-01-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uni', models.CharField(max_length=50)),
                ('full_name_ansi', models.CharField(max_length=50)),
                ('full_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Assistant Registrar'), (2, 'Section Officer'), (3, 'Administrative officer'), (4, 'Computer Oparator'), (5, 'Office Assistant')], null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('office_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/OfficeStaff/')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.department')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.university')),
            ],
            options={
                'verbose_name': 'Office Staff',
                'verbose_name_plural': 'Office Staffs',
                'ordering': ['joining_date', 'designation'],
            },
        ),
        migrations.RemoveField(
            model_name='externalteacher',
            name='department',
        ),
        migrations.DeleteModel(
            name='Officers',
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['joining_date', 'designation'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.university'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Professor'), (2, 'Associate Professor'), (3, 'Assistant Professor'), (4, 'Lecturer')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/Teachers/'),
        ),
        migrations.DeleteModel(
            name='ExternalTeacher',
        ),
    ]
