# Generated by Django 5.2.4 on 2025-07-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_full_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='externalteacher',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
