# Generated by Django 5.2.4 on 2026-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_officestaff_remove_externalteacher_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
