# Generated by Django 5.2.4 on 2025-07-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_short_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uni', models.CharField(max_length=50)),
                ('full_name_ansi', models.CharField(max_length=50)),
                ('full_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, choices=[('assistant_registrar', 'Assistant Registrar'), ('section_officer', 'Section Officer'), ('computer_oparator', 'Computer Oparator'), ('office_assistant', 'Office Assistant')], max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('office_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['joining_date'],
            },
        ),
    ]
