# Generated by Django 6.0.1 on 2026-01-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_options_remove_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Professor'), (2, 'Associate Professor'), (3, 'Assistant Professor'), (4, 'Lecturer')], null=True),
        ),
    ]
