# Generated by Django 6.0.1 on 2026-01-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='designation',
        ),
    ]
