# Generated by Django 5.2 on 2025-05-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ansi', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.CharField(choices=[('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=20)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Masters', 'Masters'), ('MPhil', 'MPhil'), ('PhD', 'PhD'), ('EMTIS 1 year', 'EMTIS 1 year'), ('EMTIS 2 year', 'EMTIS 2 year')], max_length=50)),
                ('chairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chairman_committees', to='teachers.teacher')),
                ('external_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_committees', to='teachers.externalteacher')),
                ('member', models.ManyToManyField(blank=True, null=True, related_name='member_committees', to='teachers.teacher')),
            ],
        ),
    ]
