# Generated by Django 5.2 on 2026-01-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ansi', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('3rd Semester', '3rd Semester'), ('4th Semester', '4th Semester'), ('5th Semester', '5th Semester'), ('6th Semester', '6th Semester'), ('7th Semester', '7th Semester'), ('8th Semester', '8th Semester')], max_length=20, null=True)),
                ('course_credits', models.IntegerField(default=3)),
                ('exam_hours', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='ExamCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ansi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseExaminer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner_type', models.CharField(choices=[('Fist Examiner', 'Fist Examiner'), ('Second Examiner', 'Second Examiner'), ('Third Examiner', 'Third Examiner')], default='primary', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to='academic.course')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_examinations', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name_en', models.CharField(max_length=100)),
                ('department_name_ansi', models.CharField(max_length=100)),
                ('department_name_uni', models.CharField(max_length=100)),
                ('current_department_head', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('chief_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_inspector', to='teachers.teacher')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='academic.course')),
                ('inspectors', models.ManyToManyField(blank=True, related_name='inspectors', to='teachers.teacher')),
                ('exam_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_committee', to='academic.examcommittee')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairman', 'Chairman'), ('member', 'Member'), ('external_member', 'External Member'), ('coordinator', 'Coordinator')], max_length=20)),
                ('rank', models.PositiveSmallIntegerField(help_text='Lower number = higher priority')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='academic.examcommittee')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ansi', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('MPhil', 'MPhil'), ('PhD', 'PhD'), ('EMTIS 1 year', 'EMTIS 1 year'), ('EMTIS 2 year', 'EMTIS 2 year')], max_length=50)),
                ('admission_session', models.CharField(choices=[('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=20)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.academicyear')),
            ],
        ),
        migrations.AddField(
            model_name='examcommittee',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_committee', to='academic.program'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='academic.program')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.syllabus'),
        ),
    ]
