# Generated by Django 5.2.4 on 2026-01-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-admission_session']},
        ),
    ]
