# Generated by Django 5.2 on 2025-05-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('teachers', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcommittee',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member_committees', to='teachers.teacher'),
        ),
    ]
