# Generated by Django 5.2 on 2025-05-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_examcommittee_member'),
        ('teachers', '0002_alter_teacher_full_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('chief_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_inspector', to='teachers.teacher')),
                ('exam_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_committee', to='academic.examcommittee')),
                ('inspectors', models.ManyToManyField(blank=True, related_name='inspectors', to='teachers.teacher')),
            ],
        ),
    ]
