# Generated by Django 6.0.1 on 2026-01-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_program_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexaminer',
            name='examiner_type',
            field=models.CharField(choices=[('First Examiner', 'First Examiner'), ('Second Examiner', 'Second Examiner'), ('Third Examiner', 'Third Examiner')], default='primary', max_length=50),
        ),
    ]
