# Generated by Django 5.2.1 on 2025-05-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('name_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ansi', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Masters', 'Masters'), ('MPhil', 'MPhil'), ('PhD', 'PhD'), ('EMTIS 1 year', 'EMTIS 1 year'), ('EMTIS 2 year', 'EMTIS 2 year')], max_length=50)),
                ('session', models.CharField(choices=[('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=20)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='examcommittee',
            name='level',
        ),
        migrations.RemoveField(
            model_name='examcommittee',
            name='session',
        ),
        migrations.RemoveField(
            model_name='examcommittee',
            name='year',
        ),
        migrations.AddField(
            model_name='examcommittee',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_committee', to='academic.program'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('course_credits', models.IntegerField(default=3)),
                ('exam_hours', models.IntegerField(default=4)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='academic.program')),
            ],
        ),
    ]
