# Generated by Django 6.0.1 on 2026-01-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_courseexaminer_examiner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_committee',
        ),
    ]
