# Generated by Django 5.2.1 on 2025-05-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_program_remove_examcommittee_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='course_credits',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='exam_hours',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('course_credits', models.IntegerField(default=3)),
                ('exam_hours', models.IntegerField(default=4)),
                ('syllabus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.syllabus')),
            ],
        ),
    ]
