# Generated by Django 6.0.1 on 2026-01-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_exam_exam_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='room_number',
            field=models.CharField(blank=True, choices=[('Room 101', 'Room 101'), ('Room 102', 'Room 102')], max_length=50, null=True),
        ),
    ]
