# Generated by Django 5.2.1 on 2025-05-23 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_syllabus_course_code_and_more'),
        ('teachers', '0002_alter_teacher_full_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='examin_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_as_examiner1', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='examin_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_as_examiner2', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='examin_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_as_examiner3', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='examin_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_as_examiner4', to='teachers.teacher'),
        ),
    ]
