# Generated by Django 6.0.1 on 2026-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_exam_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='room_number',
            field=models.CharField(blank=True, choices=[('Room 101', 'Room 101'), ('Room 102', 'Room 102'), ('Room 103', 'Room 103'), ('Room 104', 'Room 104')], default='Room 103', max_length=50, null=True),
        ),
    ]
