# Generated by Django 6.0.1 on 2026-01-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_exam_room_number'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('regular', 'Regular'), ('retake', 'Retake'), ('improvement', 'Improvement'), ('special', 'Special')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('room_number', models.CharField(blank=True, choices=[('Room 101', 'Room 101'), ('Room 102', 'Room 102'), ('Room 103', 'Room 103'), ('Room 104', 'Room 104')], default='Room 103', max_length=50, null=True)),
                ('chief_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_inspector', to='teachers.teacher')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_rutine', to='academic.course')),
                ('inspectors', models.ManyToManyField(blank=True, related_name='inspectors', to='teachers.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddConstraint(
            model_name='examrutine',
            constraint=models.UniqueConstraint(fields=('course', 'exam_type'), name='unique_exam_type_per_course'),
        ),
    ]
