# Generated by Django 5.2.1 on 2025-05-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_course_examin_1_course_examin_2_course_examin_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='academic.course'),
        ),
    ]
