# Generated by Django 6.0.1 on 2026-01-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_examrutine_delete_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcommittee',
            name='program',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_name_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_name_ansi', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.examcommittee')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.program')),
            ],
        ),
    ]
