# Generated by Django 5.2.1 on 2025-05-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_exam_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='course_code',
            new_name='course',
        ),
    ]
