# Generated by Django 6.0.1 on 2026-01-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_remove_examcommittee_program_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='program',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('retake', 'Retake'), ('improvement', 'Improvement'), ('special', 'Special')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='examcommittee',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_committee', to='academic.program'),
        ),
    ]
