# Generated by Django 5.2.4 on 2025-07-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_rename_course_code_exam_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='program',
            old_name='session',
            new_name='admission_session',
        ),
        migrations.RemoveField(
            model_name='program',
            name='year',
        ),
        migrations.AddField(
            model_name='program',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.academicyear'),
        ),
    ]
