# Generated by Django 6.0.1 on 2026-01-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_remove_exam_program_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_type', 'exam_committee')},
        ),
    ]
