# Generated by Django 5.2.4 on 2025-07-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_academicyear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='name_ansi',
            new_name='title_ansi',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name_arabic',
            new_name='title_arabic',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name_uni',
            new_name='title_uni',
        ),
    ]
