# Generated by Django 6.0.1 on 2026-01-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_alter_exam_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_type', 'exam_committee', 'exam_name_en')},
        ),
    ]
