# Generated by Django 5.2.4 on 2025-07-25 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_remove_course_course_name_course_title_ansi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcommittee',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_commitees', to='academic.academicyear'),
        ),
    ]
