# Generated by Django 5.2.4 on 2026-01-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_alter_exam_unique_together'),
        ('teachers', '0002_officestaff_remove_externalteacher_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrutine',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='teachers.officestaff'),
        ),
    ]
