# Generated by Django 5.2.4 on 2025-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_examcommittee_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcommittee',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
