# Generated by Django 5.2.4 on 2025-07-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_examcommittee_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcommittee',
            name='academic_year',
        ),
    ]
