# Generated by Django 5.2 on 2026-01-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='utilites/pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='utilites/zips/')),
                ('image_paths', models.JSONField(default=list)),
            ],
        ),
    ]
